### ISSUE TITLE
発生したエラー一覧

### ISSUE THREAD

**Issue by pollseed** [springhackathon/twbm_task#10]
```
rake aborted!
Twitter::Error::Forbidden: Your credentials do not allow access to this resource
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/response/raise_error.rb:13:in `on_complete'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/request/multipart.rb:14:in `call'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request/multipart_with_file.rb:17:in `call'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/request.rb:33:in `perform'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:51:in `perform_request'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:96:in `perform_request_with_objects'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/utils.rb:81:in `perform_get_with_objects'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/twitter-5.14.0/lib/twitter/rest/timelines.rb:113:in `home_timeline'
/Users/shn/workspace/ruby/twbm/lib/tasks/twitter.rake:41:in `retweet'
/Users/shn/workspace/ruby/twbm/lib/tasks/twitter.rake:12:in `block (3 levels) in <top (required)>'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/Users/shn/workspace/ruby/twbm/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `each'
/Users/shn/workspace/ruby/twbm/lib/tasks/twitter.rake:11:in `block (2 levels) in <top (required)>'
Tasks: TOP => twitter:retweet
(See full trace by running task with --trace)
```

**Comment by pollseed** [comment]
oauth認証を経ていない壊れたデータが内在すると上記のエラーが発生する

対応として
☆oauth認証を経ていないデータを無視するか、論理削除する
☆エラーハンドリングで、エラーのやつは無視するなど
